import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { get, post } from "../../api/client";
import { NavHeader } from "../../components/form-screen";
import { AppButton, AppInput, Card, Screen } from "../../components/ui";
import { colors, spacing } from "../../theme";
import type { Expense, Project } from "../../types/api";

const categories=["MATERIALS","TOOLS","FUEL","VEHICLE","SUBCONTRACTOR","EQUIPMENT_HIRE","INSURANCE","PHONE_INTERNET","OFFICE","TRAVEL","OTHER"];
const gstTreatments=["GST_INCLUDED","GST_FREE","MANUAL","NOT_CLAIMABLE","UNKNOWN"];
export default function NewExpense(){
  const params=useLocalSearchParams<{projectId?:string;projectName?:string}>();
  const scopedProjectId=typeof params.projectId==="string"?params.projectId:null;
  const qc=useQueryClient(); const projects=useQuery({queryKey:["projects"],queryFn:()=>get<Project[]>("/projects"),enabled:!scopedProjectId});
  const[description,setDescription]=useState("");const[supplier,setSupplier]=useState("");const[amount,setAmount]=useState("");const[gst,setGst]=useState("");const[gstTreatment,setGstTreatment]=useState("GST_INCLUDED");const[category,setCategory]=useState("MATERIALS");const[projectId,setProject]=useState<string|null>(scopedProjectId);const[notes,setNotes]=useState("");
  const m=useMutation({mutationFn:()=>post<Expense>("/expenses",{description,supplier:supplier||null,category,status:"PAID",amount:Number(amount),gstAmount:Number(gst||0),gstTreatment,gstClaimable:["GST_INCLUDED","MANUAL"].includes(gstTreatment),expenseDate:new Date().toISOString(),paidAt:new Date().toISOString(),projectId,notes:notes||null}),onSuccess:async e=>{await Promise.all([qc.invalidateQueries({queryKey:["expenses"]}),...(scopedProjectId?[qc.invalidateQueries({queryKey:["project",scopedProjectId]})]:[])]);router.replace(scopedProjectId?`/projects/${scopedProjectId}`:`/expenses/${e.id}`)}});
  return <Screen><NavHeader title="New expense"/><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==="ios"?"padding":undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><Card style={styles.form}><AppInput label="Description" value={description} onChangeText={setDescription}/><AppInput label="Supplier" value={supplier} onChangeText={setSupplier}/><Text style={styles.label}>Category</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{categories.map(x=><Pressable key={x} onPress={()=>setCategory(x)} style={[styles.chip,category===x&&styles.selected]}><Text style={styles.chipText}>{x.replaceAll("_"," ")}</Text></Pressable>)}</ScrollView><AppInput label="Amount (inc. GST)" value={amount} onChangeText={setAmount} keyboardType="decimal-pad"/><Text style={styles.label}>GST treatment</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{gstTreatments.map(x=><Pressable key={x} onPress={()=>setGstTreatment(x)} style={[styles.chip,gstTreatment===x&&styles.selected]}><Text style={styles.chipText}>{x.replaceAll("_"," ")}</Text></Pressable>)}</ScrollView>{gstTreatment==="MANUAL"?<AppInput label="GST amount shown" value={gst} onChangeText={setGst} keyboardType="decimal-pad"/>:null}<Text style={styles.meta}>GST credits remain subject to documentation review.</Text><Text style={styles.label}>Project</Text>{scopedProjectId?<View style={styles.locked}><Text style={styles.chipText}>{params.projectName??"Current project"}</Text></View>:<ScrollView horizontal showsHorizontalScrollIndicator={false}>{projects.data?.map(x=><Pressable key={x.id} onPress={()=>setProject(projectId===x.id?null:x.id)} style={[styles.chip,projectId===x.id&&styles.selected]}><Text style={styles.chipText}>{x.name}</Text></Pressable>)}</ScrollView>}<AppInput label="Notes" value={notes} onChangeText={setNotes} multiline/>{m.error?<Text style={styles.error}>{m.error.message}</Text>:null}<AppButton title="Save expense" loading={m.isPending} disabled={description.trim().length<2||!(Number(amount)>0)} onPress={()=>m.mutate()}/></Card></ScrollView></KeyboardAvoidingView></Screen>
}
const styles=StyleSheet.create({content:{padding:spacing.md},form:{gap:spacing.md},label:{fontWeight:"700",color:colors.text},meta:{fontSize:12,color:colors.muted},chip:{padding:11,borderRadius:99,backgroundColor:colors.surfaceAlt,marginRight:8},selected:{backgroundColor:"#FEF3C7",borderWidth:1,borderColor:colors.primary},locked:{padding:14,borderRadius:12,backgroundColor:colors.surfaceAlt,borderWidth:1,borderColor:colors.border},chipText:{fontWeight:"700",fontSize:12,color:colors.text},error:{color:colors.danger}});
