import { useQuery } from "@tanstack/react-query";
import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { get } from "../../api/client";
import { NavHeader } from "../../components/form-screen";
import { AppButton, Card, ErrorState, LoadingState, MoneyValue, Screen, StatusBadge } from "../../components/ui";
import { colors, spacing } from "../../theme";
import type { ProjectOverview } from "../../types/api";

type Tab="overview"|"expenses"|"receipts"|"invoices"|"subcontractors"|"more";
const tabs: {key:Tab;label:string}[]=[{key:"overview",label:"Overview"},{key:"expenses",label:"Expenses"},{key:"receipts",label:"Receipts"},{key:"invoices",label:"Invoices"},{key:"subcontractors",label:"Subcontractors"},{key:"more",label:"More"}];
export default function ProjectDetail(){
  const{id}=useLocalSearchParams<{id:string}>();const[tab,setTab]=useState<Tab>("overview");
  const q=useQuery({queryKey:["project",id],queryFn:()=>get<ProjectOverview>(`/analytics/projects/${id}`),enabled:!!id});
  if(q.isLoading)return <LoadingState/>;if(q.isError)return <ErrorState message={q.error.message} retry={q.refetch}/>;
  const{project:p,financials:f}=q.data!;const receiptCount=p.expenses.reduce((n,x)=>n+(x.receipts?.length??0),0);
  return <Screen><NavHeader title={p.name}/><ScrollView refreshControl={<RefreshControl refreshing={q.isRefetching} onRefresh={q.refetch}/>} contentContainerStyle={styles.content}><Card style={styles.hero}><View style={styles.row}><Text style={styles.name}>{p.name}</Text><StatusBadge status={p.status}/></View><Text style={styles.meta}>{p.customer?`${p.customer.firstName} ${p.customer.lastName}`:p.clientName??"No customer"}</Text>{p.address?<Text style={styles.meta}>{p.address}</Text>:null}<MoneyValue value={p.quotedValue??0}/></Card><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.tabs}>{tabs.map(x=><Pressable key={x.key} onPress={()=>setTab(x.key)} style={[styles.tab,tab===x.key&&styles.tabActive]}><Text style={[styles.tabText,tab===x.key&&styles.tabTextActive]}>{x.label}</Text></Pressable>)}</ScrollView>
  {tab==="overview"&&<><Card style={styles.cockpit}><Text style={styles.itemTitle}>Project financial position</Text>{f.messages.map(x=><Text key={x} style={styles.message}>{x}</Text>)}</Card><View style={styles.grid}>{[["Quoted value",f.quotedValue],["Invoice total",f.invoiceTotal],["Customer payments",f.customerPayments],["Customer outstanding",f.customerOutstanding],["Materials / expenses",f.expenses],["Subcontractor agreed",f.subcontractorAgreed],["Subcontractor paid",f.subcontractorPaid],["Subcontractor outstanding",f.subcontractorOutstanding],["Estimated total cost",f.estimatedTotalCost],["Estimated profit",f.estimatedProfit],["Cash received",f.cashReceived],["Cash paid",f.cashPaid],["Current cash position",f.cashPosition]].map(([label,value])=><Card key={label} style={styles.metric}><Text style={styles.label}>{label}</Text><MoneyValue value={value}/></Card>)}</View><Card style={styles.actions}><Text style={styles.itemTitle}>Estimate vs actual</Text><Text style={styles.meta}>Estimated revenue {money(f.estimateVsActual.estimatedRevenue)} · committed revenue {money(f.estimateVsActual.committedRevenue)}</Text><Text style={styles.meta}>Committed cost {money(f.estimateVsActual.actualCommittedCost)} · margin {f.estimatedMargin.toFixed(1)}%</Text></Card><Text style={styles.section}>Quick actions</Text><Card style={styles.actions}><AppButton title="Add expense" onPress={()=>router.push({pathname:"/expenses/new",params:{projectId:p.id,projectName:p.name}})}/><AppButton title="Upload receipt" variant="secondary" disabled={!p.expenses.length} onPress={()=>p.expenses[0]&&router.push(`/expenses/${p.expenses[0].id}`)}/><AppButton title="View invoices" variant="secondary" onPress={()=>setTab("invoices")}/><AppButton title="Add subcontractor work" variant="secondary" onPress={()=>setTab("subcontractors")}/></Card>{p.status==="COMPLETED"?<Card style={styles.actions}><Text style={styles.itemTitle}>Completion review</Text>{f.completionChecklist.map(x=><Text key={x.key} style={[styles.meta,!x.ok&&{color:colors.warning}]}>{x.ok?"✓":"⚠"} {x.label}</Text>)}</Card>:null}</>}
  {tab==="expenses"&&<Section title="Expenses" empty="No expenses yet" message="Record your first cost for this project." action={<AppButton title="Add expense" onPress={()=>router.push({pathname:"/expenses/new",params:{projectId:p.id,projectName:p.name}})}/>}>{p.expenses.map(x=><Pressable key={x.id} onPress={()=>router.push(`/expenses/${x.id}`)}><Card style={styles.item}><View style={{flex:1}}><Text style={styles.itemTitle}>{x.description}</Text><Text style={styles.meta}>{x.supplier??x.category} · {x.receipts?.length??0} receipt(s)</Text></View><MoneyValue value={x.amount}/></Card></Pressable>)}</Section>}
  {tab==="receipts"&&<Section title={`Receipts (${receiptCount})`} empty="No receipts" message="Upload receipts against a project expense.">{p.expenses.map(x=><Pressable key={x.id} onPress={()=>router.push(`/expenses/${x.id}`)}><Card style={styles.item}><View style={{flex:1}}><Text style={styles.itemTitle}>{x.supplier??x.description}</Text><Text style={styles.meta}>{x.description} · {x.receipts?.length??0} receipt(s)</Text></View><Text style={styles.link}>Open</Text></Card></Pressable>)}</Section>}
  {tab==="invoices"&&<Section title="Invoices" empty="No invoices yet" message="Create invoices on web; project and customer context are shown here.">{p.invoices.map(x=><Pressable key={x.id} onPress={()=>router.push(`/invoices/${x.id}`)}><Card style={styles.item}><View style={{flex:1}}><Text style={styles.itemTitle}>{x.invoiceNumber}</Text><Text style={styles.meta}>{x.status.replaceAll("_"," ")} · Owing ${Number(x.balanceDue).toFixed(2)}</Text></View><MoneyValue value={x.totalAmount}/></Card></Pressable>)}</Section>}
  {tab==="subcontractors"&&<Section title="Subcontractor work" empty="No subcontractors yet" message="Add subcontractor work from web or open a subcontractor below.">{p.subcontractorProjectCosts.map(x=><Pressable key={x.id} onPress={()=>router.push(`/subcontractors/${x.subcontractor.id}`)}><Card style={styles.item}><View style={{flex:1}}><Text style={styles.itemTitle}>{x.subcontractor.businessName??x.subcontractor.firstName}</Text><Text style={styles.meta}>{x.description??x.status} · Owing ${Number(x.amountPending).toFixed(2)}</Text></View><MoneyValue value={x.agreedAmount}/></Card></Pressable>)}</Section>}
  {tab==="more"&&<><Section title="Quotes" empty="No quotes yet" message="Project quotes will appear here.">{(p as ProjectOverview["project"]&{quotes?:{id:string;quoteNumber:string;title:string;totalAmount:string|number}[]}).quotes?.map(x=><Pressable key={x.id} onPress={()=>router.push(`/quotes/${x.id}`)}><Card style={styles.item}><View style={{flex:1}}><Text style={styles.itemTitle}>{x.quoteNumber}</Text><Text style={styles.meta}>{x.title}</Text></View><MoneyValue value={x.totalAmount}/></Card></Pressable>)}</Section><Card style={styles.actions}><Text style={styles.itemTitle}>Project customer</Text><Text style={styles.meta}>{p.customer?`${p.customer.firstName} ${p.customer.lastName}`:"No customer linked"}</Text>{p.customer?<AppButton title="View customer" variant="secondary" onPress={()=>router.push(`/customers/${p.customer!.id}`)}/>:null}</Card></>}
  </ScrollView></Screen>
}
function Section({title,empty,message,action,children}:{title:string;empty:string;message:string;action?:React.ReactNode;children:React.ReactNode}){const has=Array.isArray(children)?children.length>0:Boolean(children);return <View><View style={styles.sectionHead}><Text style={styles.section}>{title}</Text>{action}</View>{has?children:<Card style={styles.empty}><Text style={styles.itemTitle}>{empty}</Text><Text style={styles.meta}>{message}</Text>{action}</Card>}</View>}
const money=(v:number)=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD",maximumFractionDigits:0}).format(v);const styles=StyleSheet.create({content:{paddingBottom:40},hero:{margin:spacing.md,gap:8},cockpit:{marginHorizontal:spacing.md,gap:8,backgroundColor:colors.text,borderColor:colors.text},message:{color:"#DDE9E2",lineHeight:20},row:{flexDirection:"row",gap:spacing.md,alignItems:"center"},name:{flex:1,fontSize:23,fontWeight:"900",color:colors.text},meta:{color:colors.muted},tabs:{paddingHorizontal:spacing.md,gap:8,paddingBottom:spacing.md},tab:{paddingHorizontal:15,paddingVertical:10,borderRadius:99,backgroundColor:colors.surfaceAlt},tabActive:{backgroundColor:colors.text},tabText:{fontWeight:"800",color:colors.muted},tabTextActive:{color:"white"},grid:{flexDirection:"row",flexWrap:"wrap",gap:spacing.sm,paddingHorizontal:spacing.md},metric:{width:"48%",gap:8},label:{color:colors.muted,fontSize:12},sectionHead:{paddingHorizontal:spacing.md,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},section:{fontSize:18,fontWeight:"900",color:colors.text,marginVertical:spacing.md},actions:{marginHorizontal:spacing.md,gap:spacing.sm},item:{marginHorizontal:spacing.md,marginBottom:spacing.sm,flexDirection:"row",alignItems:"center",gap:spacing.sm},itemTitle:{fontWeight:"800",color:colors.text},link:{fontWeight:"800",color:colors.primaryDark},empty:{marginHorizontal:spacing.md,alignItems:"center",gap:8}});
