import { Prisma } from "../../generated/prisma/client.js";
import { prisma } from "../../lib/prisma.js";
import { residentIncomeTax, suggestedReserve } from "./financial-calculations.js";

const zero=()=>new Prisma.Decimal(0);const n=(v:unknown)=>Number(v??0);const sum=<T>(xs:T[],f:(x:T)=>unknown)=>xs.reduce((s,x)=>s.plus(new Prisma.Decimal(String(f(x)??0))),zero());
export function financialYearRange(year:string){const match=/^(\d{4})-(\d{2})$/.exec(year);if(!match)throw new Error("Unsupported financial year.");const startYear=Number(match[1]);return {from:new Date(`${startYear}-07-01T00:00:00+09:30`),to:new Date(`${startYear+1}-07-01T00:00:00+09:30`)};}
export function periodRange(preset:string|undefined,from?:string,to?:string){const now=new Date();if(preset==="custom"&&from&&to)return{from:new Date(from),to:new Date(new Date(to).getTime()+86_400_000)};if(preset==="month")return{from:new Date(now.getFullYear(),now.getMonth(),1),to:new Date(now.getFullYear(),now.getMonth()+1,1)};if(preset==="previous-quarter"){const q=Math.floor(now.getMonth()/3);return{from:new Date(now.getFullYear(),(q-1)*3,1),to:new Date(now.getFullYear(),q*3,1)}}if(preset==="financial-year")return financialYearRange(now.getMonth()>=6?`${now.getFullYear()}-${String(now.getFullYear()+1).slice(-2)}`:`${now.getFullYear()-1}-${String(now.getFullYear()).slice(-2)}`);const q=Math.floor(now.getMonth()/3);return{from:new Date(now.getFullYear(),q*3,1),to:new Date(now.getFullYear(),q*3+3,1)};}

export async function getMoneyHub(ownerId:string){const[invoices,costs]=await Promise.all([prisma.invoice.findMany({where:{ownerId,status:{notIn:["DRAFT","CANCELLED"]},balanceDue:{gt:0}},include:{customer:true,project:true},orderBy:{dueDate:"asc"}}),prisma.subcontractorProjectCost.findMany({where:{ownerId,status:{not:"CANCELLED"},amountPending:{gt:0}},include:{subcontractor:true,project:true},orderBy:{updatedAt:"desc"}})]);const owed=sum(invoices,x=>x.balanceDue);const owe=sum(costs,x=>x.amountPending);return{owedToYou:owed,youOwe:owe,netPosition:owed.minus(owe),receivables:invoices.map(x=>({...x,outstanding:x.balanceDue,daysOverdue:x.dueDate?Math.max(0,Math.floor((Date.now()-x.dueDate.getTime())/86_400_000)):0})),payables:costs.map(x=>({...x,outstanding:x.amountPending}))};}

export async function getTaxSummary(ownerId:string,preset?:string,from?:string,to?:string){const owner=await prisma.user.findUniqueOrThrow({where:{id:ownerId}});const range=periodRange(preset,from,to);const[invoices,payments,expenses,payg]=await Promise.all([prisma.invoice.findMany({where:{ownerId,status:{notIn:["DRAFT","CANCELLED"]},issueDate:{gte:range.from,lt:range.to}}}),prisma.payment.findMany({where:{ownerId,paidAt:{gte:range.from,lt:range.to}},include:{invoice:true}}),prisma.expense.findMany({where:{ownerId,expenseDate:{gte:range.from,lt:range.to}},include:{receipts:true}}),prisma.paygInstalment.findMany({where:{ownerId,paidAt:{gte:range.from,lt:range.to}},orderBy:{paidAt:"desc"}})]);if(!owner.gstRegistered)return{registered:false,range,settings:owner,gst:{g1:0,gstOnSales:0,confirmedCredits:0,potentialCredits:0,netGst:0,missingReceipts:expenses.filter(x=>!x.receipts.length).length,unknownItems:expenses.filter(x=>x.gstTreatment==="UNKNOWN").length},profit:null,tax:null,payg};const cash=owner.gstAccountingMethod==="CASH";const salesBase=cash?sum(payments,x=>x.amount):sum(invoices,x=>x.totalAmount);const gstOnSales=cash?sum(payments,x=>new Prisma.Decimal(x.amount).div(x.invoice.totalAmount).times(x.invoice.gstAmount)):sum(invoices,x=>x.gstAmount);const relevantExpenses=cash?expenses.filter(x=>x.paidAt&&x.paidAt>=range.from&&x.paidAt<range.to):expenses;const confirmed=relevantExpenses.filter(x=>x.gstClaimable&&x.receipts.length>0&&x.gstTreatment!=="UNKNOWN");const pending=relevantExpenses.filter(x=>x.gstClaimable&&x.receipts.length===0);const credits=sum(confirmed,x=>x.gstAmount);const potential=sum(pending,x=>x.gstAmount);const netGst=gstOnSales.minus(credits);const incomeExGst=salesBase.minus(gstOnSales);const expenseExGst=sum(relevantExpenses.filter(x=>x.category!=="SUBCONTRACTOR"),x=>new Prisma.Decimal(x.amount).minus(x.gstClaimable?x.gstAmount:0));const subCosts=await prisma.subcontractorProjectCost.findMany({where:{ownerId,status:{not:"CANCELLED"},createdAt:{gte:range.from,lt:range.to}}});const businessProfit=incomeExGst.minus(expenseExGst).minus(sum(subCosts,x=>x.agreedAmount));const calculatorIncome=businessProfit.plus(owner.otherTaxableIncome).minus(owner.additionalDeductions);const indicative=owner.taxProfile==="AUSTRALIAN_RESIDENT_INDIVIDUAL"?residentIncomeTax(calculatorIncome.toNumber(),owner.taxFinancialYear):null;const paygPaid=sum(payg,x=>x.amount);return{registered:true,range,settings:owner,gst:{g1:salesBase,gstOnSales,confirmedCredits:credits,potentialCredits:potential,netGst,missingReceipts:expenses.filter(x=>!x.receipts.length).length,unknownItems:expenses.filter(x=>x.gstTreatment==="UNKNOWN").length},profit:{incomeExGst,expensesExGst:expenseExGst,subcontractorCosts:sum(subCosts,x=>x.agreedAmount),businessProfit},tax:{calculatorIncome,indicativeIncomeTax:indicative,paygPaid,suggestedReserve:indicative===null?null:suggestedReserve(netGst.toNumber(),indicative,paygPaid.toNumber()),supported:indicative!==null},payg};}

export async function getWeeklyCheck(ownerId:string){const to=new Date();const from=new Date(to.getTime()-7*86_400_000);const overview=await getMoneyHub(ownerId);const[payments,expenses,newInvoices,missing]=await Promise.all([prisma.payment.findMany({where:{ownerId,paidAt:{gte:from,lte:to}}}),prisma.expense.findMany({where:{ownerId,expenseDate:{gte:from,lte:to}}}),prisma.invoice.findMany({where:{ownerId,issueDate:{gte:from,lte:to},status:{not:"CANCELLED"}}}),prisma.expense.findMany({where:{ownerId,receipts:{none:{}}}})]);const issues=[...overview.receivables.filter(x=>x.daysOverdue>0).map(x=>({type:"OVERDUE",title:`${x.invoiceNumber} is ${x.daysOverdue} days overdue`,path:`/invoices/${x.id}`})),...(missing.length?[{type:"RECEIPT",title:`${missing.length} expenses are missing receipts`,path:"/expenses"}]:[]),...overview.payables.slice(0,3).map(x=>({type:"PAYABLE",title:`${x.subcontractor.businessName||x.subcontractor.firstName} is owed $${n(x.amountPending).toFixed(2)}`,path:`/subcontractors/${x.subcontractorId}`}))];return{range:{from,to},moneyReceived:sum(payments,x=>x.amount),moneySpent:sum(expenses,x=>x.amount),newInvoices:sum(newInvoices,x=>x.totalAmount),customerOutstanding:overview.owedToYou,subcontractorOutstanding:overview.youOwe,issues};}

export async function getCashflow(ownerId:string,days=14){const from=new Date();const to=new Date(from.getTime()+days*86_400_000);const[invoices,expenses]=await Promise.all([prisma.invoice.findMany({where:{ownerId,status:{notIn:["DRAFT","CANCELLED","PAID"]},dueDate:{gte:from,lte:to},balanceDue:{gt:0}},include:{customer:true}}),prisma.expense.findMany({where:{ownerId,status:{not:"PAID"},dueDate:{gte:from,lte:to}}})]);const comingIn=sum(invoices,x=>x.balanceDue),goingOut=sum(expenses,x=>x.amount);return{range:{from,to},comingIn:invoices,totalComingIn:comingIn,goingOut:expenses,totalGoingOut:goingOut,netExpected:comingIn.minus(goingOut),qualification:"Expected if invoices are paid and known expenses are settled on their due dates. Subcontractor costs without due dates are excluded."};}

export async function getSubcontractorStatement(ownerId:string,subcontractorId:string,from:Date,to:Date){const sub=await prisma.subcontractor.findFirst({where:{id:subcontractorId,ownerId}});if(!sub)return null;const costs=await prisma.subcontractorProjectCost.findMany({where:{ownerId,subcontractorId,status:{not:"CANCELLED"},createdAt:{gte:from,lt:to}},include:{project:true,payments:{where:{paidAt:{gte:from,lt:to}},orderBy:{paidAt:"asc"}}},orderBy:{createdAt:"asc"}});const agreed=sum(costs,x=>x.agreedAmount),paid=sum(costs.flatMap(x=>x.payments),x=>x.amount);return{subcontractor:sub,range:{from,to},entries:costs,totalAgreed:agreed,totalPaid:paid,balance:agreed.minus(paid)};}
