export interface User { id: string; email: string; firstName: string; lastName: string; businessName: string | null; abn: string | null; phone: string | null; address: string | null; tradeType: string | null; gstRegistered: boolean }
export interface Customer { id: string; firstName: string; lastName: string; businessName: string | null; email: string | null; phone: string | null; address: string | null; abn: string | null; notes: string | null; isArchived: boolean }
export interface Project { id: string; name: string; description: string | null; clientName: string | null; address: string | null; quotedValue: string | number | null; status: "ACTIVE" | "COMPLETED" | "ARCHIVED"; startDate: string | null; endDate: string | null; customerId: string | null; customer?: Customer | null }
export interface Receipt { id: string; originalName: string; mimeType: string; fileSize: number; createdAt: string }
export interface Expense { id: string; description: string; supplier: string | null; category: string; status: string; amount: string | number; gstAmount: string | number; expenseDate: string; dueDate: string | null; notes: string | null; projectId: string | null; project?: Project | null; receipts?: Receipt[] }
export interface Payment { id: string; amount: string | number; method?: string; paidAt: string; reference: string | null; notes: string | null }
export interface Invoice { id: string; invoiceNumber: string; title: string; status: string; issueDate: string; dueDate: string | null; totalAmount: string | number; amountPaid: string | number; balanceDue: string | number; customer: Customer; project: Project | null; items: { id: string; description: string; quantity: string | number; unitPrice: string | number; lineTotal: string | number }[]; payments: Payment[] }
export interface Quote { id: string; quoteNumber: string; title: string; description: string | null; status: string; issueDate: string; expiryDate: string | null; totalAmount: string | number; customer: Customer; project: Project | null; items: { id: string; description: string; quantity: string | number; unitPrice: string | number; lineTotal: string | number }[] }
export interface Subcontractor { id: string; firstName: string; lastName: string | null; businessName: string | null; abn: string | null; email: string | null; phone: string | null; address: string | null; notes: string | null }
export interface SubcontractorCost { id: string; description: string | null; rateType: string; rate: string | number | null; quantity: string | number | null; agreedAmount: string | number; amountPaid: string | number; amountPending: string | number; status: string; subcontractor: Subcontractor; project: Project; payments: Payment[] }
export interface Financials { quotedValue: number; invoiceTotal: number; customerPayments: number; customerOutstanding: number; expenses: number; subcontractorAgreed: number; subcontractorPaid: number; subcontractorOutstanding: number; estimatedProfit: number }
export interface BusinessOverview { business: { firstName: string; businessName: string | null; abn: string | null }; kpis: { activeProjects: number; totalInvoiced: number; paymentsReceived: number; customerOutstanding: number; expenses: number; expensesPaid: number; subcontractorCosts: number; subcontractorPaid: number; subcontractorOutstanding: number; estimatedProfit: number; cashPosition: number }; receivables: { id: string; invoiceNumber: string; customer: Customer; project: Project | null; dueDate: string | null; status: string; outstanding: string | number }[]; payables: { id: string; subcontractor: Subcontractor; project: Project; status: string; outstanding: string | number }[]; activeProjects: { id: string; name: string; clientName: string | null; status: string; financials: Financials }[]; recentActivity: { id: string; type: string; title: string; description: string; occurredAt: string }[] }
export interface ProjectOverview { project: Project & { invoices: Invoice[]; expenses: Expense[]; subcontractorProjectCosts: SubcontractorCost[] }; financials: Financials }
export interface CustomerOverview { customer: Customer & { projects: Project[]; invoices: Invoice[] }; financials: { totalInvoiced: number; totalPaid: number; outstanding: number } }
