import { useState } from "react";
import type { TrendPoint } from "../types";
import { aud, chartPath } from "../dashboard-utils";

export function MoneyChart({ data }: { data: TrendPoint[] }) {
  const [range, setRange] = useState<6|12>(12); const [active, setActive] = useState<number | null>(null); const lastActual=Math.max(data.findLastIndex((point)=>point.kind==="ACTUAL"),0); const points = range===12?data:data.slice(Math.max(0,lastActual-5),lastActual+1); const width=900,height=250; const max=Math.max(...points.flatMap((p)=>[p.revenue,p.expenses]),1)*1.12;
  return <section className="surface-card p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-[.15em] text-blue-600">Cash movement</p><h2 className="mt-1 text-xl font-black">Money in vs money out</h2><p className="mt-1 text-sm text-slate-500">Recorded payments and expenses by month.</p></div><div className="flex rounded-xl bg-slate-100 p-1">{([6,12] as const).map((value)=><button key={value} onClick={()=>setRange(value)} className={`rounded-lg px-3 py-2 text-xs font-bold ${range===value?"bg-white text-slate-900 shadow-sm":"text-slate-500"}`}>{value} months</button>)}</div></div>
    <div className="relative mt-7 overflow-x-auto"><svg viewBox={`-24 -18 ${width+48} ${height+70}`} className="min-w-[620px]" role="img" aria-label="Monthly revenue and expense line chart">
      {[0,.25,.5,.75,1].map((v)=><line key={v} x1="0" x2={width} y1={height*v} y2={height*v} stroke="#e8e7e2" strokeDasharray="4 6"/>)}
      <path d={chartPath(points,"revenue",width,height,max)} fill="none" stroke="#059669" strokeWidth="5" strokeLinecap="round" strokeLinejoin="round"/><path d={chartPath(points,"expenses",width,height,max)} fill="none" stroke="#64748b" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/>
      {points.map((point,index)=>{const x=index/Math.max(points.length-1,1)*width; return <g key={point.month} onMouseEnter={()=>setActive(index)} onMouseLeave={()=>setActive(null)}><rect x={x-32} y="0" width="64" height={height} fill="transparent"/><circle cx={x} cy={height-point.revenue/max*height} r={active===index?7:4} fill="#059669" stroke="white" strokeWidth="3"/><text x={x} y={height+29} textAnchor="middle" fontSize="13" fill="#687386">{point.month}</text></g>})}
    </svg>{active!=null&&<div className="pointer-events-none absolute left-1/2 top-2 z-10 w-44 -translate-x-1/2 rounded-xl bg-slate-950 p-3 text-xs text-white shadow-xl"><strong>{points[active].month}</strong><p className="mt-2 flex justify-between text-slate-300"><span>Money in</span><b className="text-white">{aud(points[active].revenue,true)}</b></p><p className="mt-1 flex justify-between text-slate-300"><span>Money out</span><b className="text-white">{aud(points[active].expenses,true)}</b></p><p className="mt-1 flex justify-between text-slate-300"><span>Profit</span><b className="text-white">{aud(points[active].profit,true)}</b></p></div>}</div>
    <div className="mt-2 flex gap-5 text-xs font-bold text-slate-500"><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-emerald-600"/>Money in</span><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-slate-500"/>Money out</span></div>
  </section>;
}

export function ForecastChart({ data }: { data: TrendPoint[] }) { const width=900,height=180; const max=Math.max(...data.map((p)=>p.revenue),1)*1.12; const actual=data.filter(p=>p.kind==="ACTUAL"); const firstForecast=Math.max(actual.length-1,0); const projected=data.slice(firstForecast); return <div className="mt-6 overflow-x-auto"><svg viewBox={`-20 -15 ${width+40} ${height+50}`} className="min-w-[620px]" role="img" aria-label="Actual and projected monthly revenue"><path d={chartPath(actual,"revenue",width*(actual.length-1)/11,height,max)} fill="none" stroke="#059669" strokeWidth="5" strokeLinecap="round"/><g transform={`translate(${width*firstForecast/11} 0)`}><path d={chartPath(projected,"revenue",width*(projected.length-1)/11,height,max)} fill="none" stroke="#d97706" strokeWidth="5" strokeDasharray="10 9" strokeLinecap="round"/></g>{data.map((p,i)=><text key={p.month} x={i/11*width} y={height+28} textAnchor="middle" fontSize="12" fill="#687386">{p.month}</text>)}</svg></div>; }
