import { useQuery } from "@tanstack/react-query";
import { router } from "expo-router";
import { ArrowDownLeft, ArrowRight, BriefcaseBusiness, TrendingUp } from "lucide-react-native";
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from "react-native";
import { get } from "../../api/client";
import { Card, ErrorState, Header, LoadingState, MoneyValue, Screen, StatusBadge } from "../../components/ui";
import { colors, radius, spacing, typography } from "../../theme";
import type { BusinessOverview } from "../../types/api";

export default function Dashboard() {
  const query=useQuery({queryKey:["analytics","overview"],queryFn:()=>get<BusinessOverview>("/analytics/overview")});
  if(query.isLoading)return <LoadingState/>;
  if(query.isError)return <ErrorState message="We couldn't load your business overview." retry={query.refetch}/>;
  const data=query.data!;
  return <Screen><FlatList data={data.activeProjects.slice(0,5)} keyExtractor={(item)=>item.id} refreshControl={<RefreshControl tintColor={colors.primaryDark} refreshing={query.isRefetching} onRefresh={query.refetch}/>} contentContainerStyle={styles.content}
    ListHeaderComponent={<><Header title={`G'day, ${data.business.firstName}`} subtitle={data.business.businessName??"Here’s what matters in your business today."}/>
      <Card style={styles.primary}><View style={styles.primaryLabel}><ArrowDownLeft size={18} color="#DDE9E2"/><Text style={styles.primaryCaption}>Money received</Text></View><Text style={styles.primaryMoney}>{money(data.kpis.paymentsReceived)}</Text><Pressable onPress={()=>router.push("/outstanding")} style={styles.primaryLink}><Text style={styles.primaryLinkText}>{money(data.kpis.customerOutstanding)} still outstanding</Text><ArrowRight size={16} color="#DDE9E2"/></Pressable></Card>
      <View style={styles.metrics}><Metric label="Expenses" value={data.kpis.expenses}/><Metric label="Subcontractors owed" value={data.kpis.subcontractorOutstanding}/><Metric label="Estimated profit" value={data.kpis.estimatedProfit} positive/><View style={styles.count}><BriefcaseBusiness size={18} color={colors.info}/><Text style={styles.countValue}>{data.kpis.activeProjects}</Text><Text style={styles.metricLabel}>Active projects</Text></View></View>
      <Section title="Active projects" action="View all" onPress={()=>router.push("/(tabs)/projects")}/></>}
    renderItem={({item})=><Pressable onPress={()=>router.push(`/projects/${item.id}`)} style={({pressed})=>pressed&&{opacity:.7}}><Card style={styles.project}><View style={{flex:1}}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.clientName??"No customer linked"}</Text><Text style={styles.projectMoney}>{money(item.financials.customerOutstanding)} outstanding</Text></View><StatusBadge status={item.status}/></Card></Pressable>}
    ListFooterComponent={<>{data.recentActivity.length?<><Section title="Recent activity"/>{data.recentActivity.slice(0,4).map((item)=><View key={item.id} style={styles.activity}><View style={styles.dot}/><View style={{flex:1}}><Text style={styles.activityTitle}>{item.title}</Text><Text style={styles.meta}>{item.description}</Text></View></View>)}</>:null}</>}/>
  </Screen>;
}
function Metric({label,value,positive=false}:{label:string;value:string|number;positive?:boolean}){return <View style={styles.metric}><TrendingUp size={18} color={positive?colors.success:colors.muted}/><MoneyValue value={value}/><Text style={styles.metricLabel}>{label}</Text></View>}
function Section({title,action,onPress}:{title:string;action?:string;onPress?:()=>void}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{action?<Pressable onPress={onPress}><Text style={styles.sectionAction}>{action}</Text></Pressable>:null}</View>}
const money=(value:string|number)=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD",maximumFractionDigits:0}).format(Number(value));
const styles=StyleSheet.create({content:{paddingBottom:40},primary:{marginHorizontal:spacing.md,backgroundColor:colors.text,borderColor:colors.text,padding:spacing.lg,gap:10},primaryLabel:{flexDirection:"row",alignItems:"center",gap:8},primaryCaption:{color:"#DDE9E2",fontSize:14},primaryMoney:{color:"white",fontSize:36,fontWeight:"800",letterSpacing:-1},primaryLink:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",borderTopWidth:1,borderTopColor:"#33413E",paddingTop:12,marginTop:5},primaryLinkText:{color:"#DDE9E2",fontSize:13,fontWeight:"700"},metrics:{flexDirection:"row",flexWrap:"wrap",gap:spacing.sm,padding:spacing.md},metric:{width:"48%",minHeight:112,backgroundColor:colors.surface,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,padding:spacing.md,gap:7},count:{width:"48%",minHeight:112,backgroundColor:colors.surface,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,padding:spacing.md,gap:7},countValue:{fontSize:typography.money,fontWeight:"800",color:colors.text},metricLabel:{color:colors.muted,fontSize:13},section:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",paddingHorizontal:spacing.md,marginTop:spacing.lg,marginBottom:spacing.sm},sectionTitle:{fontSize:typography.section,fontWeight:"800",color:colors.text},sectionAction:{color:colors.primaryDark,fontWeight:"700"},project:{marginHorizontal:spacing.md,marginBottom:spacing.sm,flexDirection:"row",alignItems:"flex-start",gap:spacing.md},name:{fontSize:16,fontWeight:"800",color:colors.text},meta:{color:colors.muted,fontSize:13,lineHeight:19,marginTop:3},projectMoney:{color:colors.text,fontSize:13,fontWeight:"700",marginTop:9},activity:{flexDirection:"row",gap:12,paddingHorizontal:spacing.lg,paddingVertical:10},dot:{height:9,width:9,borderRadius:9,backgroundColor:colors.primary,marginTop:5},activityTitle:{fontWeight:"700",color:colors.text}});
