import { router } from "expo-router";
import { Bot, ChevronRight, FileText, HardHat, ReceiptText, Settings, TriangleAlert } from "lucide-react-native";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useAuth } from "../../auth/auth-context";
import { Header, Screen } from "../../components/ui";
import { colors, radius, spacing } from "../../theme";

export default function More(){const{user}=useAuth();const initials=`${user?.firstName?.[0]??""}${user?.lastName?.[0]??""}`.toUpperCase()||"TA";const links=[{title:"Subcontractors",sub:"Work, costs and recorded payments",path:"/subcontractors",Icon:HardHat},{title:"Quotes",sub:"Estimates and customer approvals",path:"/quotes",Icon:FileText},{title:"Receipts",sub:"Find receipts through project expenses",path:"/expenses",Icon:ReceiptText},{title:"Outstanding",sub:"Money owed in both directions",path:"/outstanding",Icon:TriangleAlert},{title:"Settings",sub:"Business profile and account",path:"/settings",Icon:Settings}];return <Screen><ScrollView contentContainerStyle={styles.content}><Header title="More" subtitle="Tools and account settings"/><View style={styles.profile}><View style={styles.avatar}><Text style={styles.initials}>{initials}</Text></View><View style={{flex:1}}><Text style={styles.profileName}>{user?.firstName} {user?.lastName}</Text><Text style={styles.meta}>{user?.businessName||user?.email}</Text></View></View><Text style={styles.group}>BUSINESS TOOLS</Text><View style={styles.list}>{links.map(({title,sub,path,Icon},index)=><Pressable key={title} accessibilityRole="button" onPress={()=>router.push(path as never)} style={({pressed})=>[styles.row,index<links.length-1&&styles.divider,pressed&&styles.pressed]}><View style={styles.icon}><Icon size={20} color={colors.text}/></View><View style={{flex:1}}><Text style={styles.name}>{title}</Text><Text style={styles.meta}>{sub}</Text></View><ChevronRight size={19} color={colors.muted}/></Pressable>)}</View><Text style={styles.group}>COMING LATER</Text><View style={styles.list}><View style={styles.row}><View style={styles.icon}><Bot size={20} color={colors.muted}/></View><View style={{flex:1}}><Text style={styles.name}>AI Assistant</Text><Text style={styles.meta}>Coming soon — no AI answers are generated yet.</Text></View></View></View></ScrollView></Screen>}
const styles=StyleSheet.create({content:{paddingBottom:40},profile:{marginHorizontal:spacing.md,marginBottom:spacing.lg,flexDirection:"row",alignItems:"center",gap:spacing.md},avatar:{height:52,width:52,borderRadius:26,backgroundColor:"#F4E6C5",alignItems:"center",justifyContent:"center"},initials:{fontWeight:"800",fontSize:17,color:colors.primaryDark},profileName:{fontWeight:"800",fontSize:17,color:colors.text},meta:{color:colors.muted,fontSize:13,marginTop:3,lineHeight:18},group:{fontSize:11,fontWeight:"800",letterSpacing:1,color:colors.muted,marginHorizontal:spacing.lg,marginBottom:8,marginTop:spacing.md},list:{marginHorizontal:spacing.md,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,overflow:"hidden"},row:{minHeight:72,flexDirection:"row",alignItems:"center",gap:spacing.md,paddingHorizontal:spacing.md,paddingVertical:12},divider:{borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.border},pressed:{backgroundColor:colors.surfaceAlt},icon:{height:38,width:38,borderRadius:11,backgroundColor:colors.surfaceAlt,alignItems:"center",justifyContent:"center"},name:{fontWeight:"700",fontSize:15,color:colors.text}});
