import { Alert, Linking, Share } from "react-native";
import type { User } from "../types/api";

export interface MobileShareInput { kind:"Invoice"|"Quote";number:string;customerName:string;projectName?:string|null;total:string|number;paid?:string|number;outstanding?:string|number;dueDate?:string|null; }
const money=(v:string|number)=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD"}).format(Number(v));
export function normalizePhone(phone?:string|null){if(!phone)return null;const d=phone.replace(/\D/g,"");if(d.startsWith("61")&&d.length>=10)return d;if(d.startsWith("0")&&d.length===10)return `61${d.slice(1)}`;return d.length>=8?d:null}
export function buildMobileShare(input:MobileShareInput,user:User){const business=user.businessName||`${user.firstName} ${user.lastName}`;const project=input.projectName||"Not linked";const lines=input.kind==="Invoice"?[`Invoice ${input.number}`,"",`Customer: ${input.customerName}`,`Project: ${project}`,"",`Total: ${money(input.total)}`,`Paid: ${money(input.paid??0)}`,`Outstanding: ${money(input.outstanding??input.total)}`,`Due: ${input.dueDate?new Date(input.dueDate).toLocaleDateString("en-AU",{day:"numeric",month:"short",year:"numeric"}):"Not specified"}`,"",`From ${business}`]:[`Quote ${input.number}`,"",`Customer: ${input.customerName}`,`Project: ${project}`,`Total: ${money(input.total)}`,"",`From ${business}`];const message=lines.join("\n");return{business,message,subject:`${input.kind} ${input.number} from ${business}`}}
async function open(url:string,label:string){try{const supported=await Linking.canOpenURL(url);if(!supported)throw new Error();await Linking.openURL(url)}catch{Alert.alert(`${label} unavailable`,`No compatible ${label.toLowerCase()} app could be opened.`)}}
export async function shareDocument(input:MobileShareInput,user:User){const x=buildMobileShare(input,user);try{await Share.share({title:x.subject,message:x.message})}catch{Alert.alert("Sharing unavailable","The share sheet could not be opened.")}}
export async function openContact(kind:"call"|"email"|"whatsapp",value:string){if(kind==="call")return open(`tel:${value.replace(/[^+\d]/g,"")}`,"Phone");if(kind==="email")return open(`mailto:${value}`,"Email");const phone=normalizePhone(value);if(phone)return open(`whatsapp://send?phone=${phone}`,"WhatsApp");Alert.alert("Invalid phone number","A valid phone number is required for WhatsApp.")}
