import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, ArrowLeft, Banknote, CalendarDays, CheckCircle2, CircleAlert, CircleDollarSign, FileText, MapPin, Pencil, ReceiptText, Trash2, Undo2, UserRound, UsersRound, WalletCards } from "lucide-react";
import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router";

import { getProjectOverview } from "../../analytics/api";
import { Modal } from "../../../shared/components/ui/Modal";
import { archiveProject, deleteProject, updateProject } from "../api/projects";
import { EditProjectForm } from "../components/EditProjectForm";
import type { ProjectStatus } from "../types/project";

const money = (value: string | number | null) => value === null ? "Not quoted" : new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD" }).format(Number(value));
const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat("en-AU", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)) : "Not scheduled";
const statusClasses = (status: ProjectStatus) => status === "ACTIVE" ? "bg-emerald-100 text-emerald-700" : status === "COMPLETED" ? "bg-blue-100 text-blue-700" : "bg-slate-200 text-slate-600";
const documentStatus = (status: string) => status === "PAID" || status === "ACCEPTED" ? "bg-emerald-100 text-emerald-700" : status === "OVERDUE" || status === "REJECTED" ? "bg-red-100 text-red-700" : "bg-amber-100 text-amber-700";

export function ProjectDetailsPage() {
  const { projectId } = useParams<{ projectId: string }>(); const queryClient = useQueryClient(); const navigate = useNavigate();
  const [editOpen, setEditOpen] = useState(false); const [archiveOpen, setArchiveOpen] = useState(false); const [deleteOpen, setDeleteOpen] = useState(false);
  const query = useQuery({ queryKey: ["project-overview", projectId], queryFn: () => getProjectOverview(projectId!), enabled: Boolean(projectId) });
  const refresh = async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ["project-overview", projectId] }), queryClient.invalidateQueries({ queryKey: ["project", projectId] }), queryClient.invalidateQueries({ queryKey: ["projects"] }), queryClient.invalidateQueries({ queryKey: ["business-overview"] })]); };
  const statusMutation = useMutation({ mutationFn: (status: "ACTIVE" | "COMPLETED") => updateProject(projectId!, { status }), onSuccess: refresh });
  const archiveMutation = useMutation({ mutationFn: () => archiveProject(projectId!), onSuccess: async () => { await refresh(); setArchiveOpen(false); } });
  const deleteMutation = useMutation({ mutationFn: () => deleteProject(projectId!), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["projects"] }); navigate("/projects"); } });
  if (!projectId) return <p className="rounded-2xl bg-red-50 p-6 text-red-700">Invalid project ID.</p>;
  if (query.isPending) return <div className="space-y-5 animate-pulse"><div className="h-8 w-44 rounded bg-slate-200"/><div className="h-52 rounded-2xl bg-slate-200"/><div className="grid gap-5 md:grid-cols-4">{[1,2,3,4].map((n) => <div key={n} className="h-32 rounded-2xl bg-slate-200"/>)}</div></div>;
  if (query.isError) return <div className="flex gap-3 rounded-2xl border border-red-200 bg-red-50 p-6 text-red-700"><CircleAlert/><div><strong>Project could not be loaded</strong><p className="mt-1 text-sm">{query.error.message}</p></div></div>;
  const { project, financials: f } = query.data; const isArchived = project.status === "ARCHIVED"; const isCompleted = project.status === "COMPLETED";
  const rows = [["Quoted value", f.quotedValue],["Invoices issued",f.invoiceTotal],["Customer payments",f.customerPayments],["Customer outstanding",f.customerOutstanding],["Direct expenses",f.expenses],["Subcontractor costs",f.subcontractorAgreed],["Subcontractors paid",f.subcontractorPaid],["Still owed",f.subcontractorOutstanding],["Estimated total cost",f.estimatedTotalCost],["Estimated project profit",f.estimatedProfit],["Cash received",f.cashReceived],["Cash paid",f.cashPaid],["Current cash position",f.cashPosition]] as const;
  return <>
    <Link to="/projects" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-slate-950"><ArrowLeft size={18}/>Back to projects</Link>
    <section className="mt-6 rounded-2xl border bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-start"><div><span className={`inline-flex rounded-full px-3 py-1 text-xs font-bold ${statusClasses(project.status)}`}>{project.status}</span><h1 className="mt-4 text-3xl font-bold">{project.name}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-500">{project.description || "No project description has been added yet."}</p></div><div className="flex flex-wrap gap-2"><button onClick={() => setEditOpen(true)} className="inline-flex h-11 items-center gap-2 rounded-xl bg-amber-400 px-4 text-sm font-bold"><Pencil size={18}/>Edit</button>{!isArchived && <button disabled={statusMutation.isPending} onClick={() => statusMutation.mutate(isCompleted ? "ACTIVE" : "COMPLETED")} className="inline-flex h-11 items-center gap-2 rounded-xl border px-4 text-sm font-bold">{isCompleted ? <Undo2 size={18}/> : <CheckCircle2 size={18}/>} {isCompleted ? "Mark active" : "Complete"}</button>}</div></div></section>
    <section className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{[[UserRound,"Customer",project.clientName || "Not assigned"],[MapPin,"Address",project.address || "Not provided"],[CalendarDays,"Dates",`${formatDate(project.startDate)} — ${formatDate(project.endDate)}`],[CircleDollarSign,"Quoted value",money(project.quotedValue)]].map(([Icon,label,value]) => { const CardIcon = Icon as typeof UserRound; return <article key={label as string} className="rounded-2xl border bg-white p-5 shadow-sm"><CardIcon size={20} className="text-amber-700"/><p className="mt-4 text-xs font-bold uppercase text-slate-400">{label as string}</p><p className="mt-1 font-bold">{value as string}</p></article>; })}</section>
    <section className="mt-6 overflow-hidden rounded-2xl bg-slate-950 text-white shadow-sm"><div className="border-b border-slate-800 p-6"><p className="text-xs font-bold uppercase tracking-wider text-amber-400">Project financials</p><h2 className="mt-1 text-2xl font-bold">Know the health of this job</h2><p className="mt-2 text-sm text-slate-400">Committed costs and actual cash movement are shown separately.</p></div><div className="grid gap-px bg-slate-800 md:grid-cols-3"><div className="bg-slate-950 p-6"><p className="text-sm text-slate-400">Estimated profit</p><p className={`mt-2 text-3xl font-bold ${f.estimatedProfit < 0 ? "text-red-400" : "text-emerald-400"}`}>{money(f.estimatedProfit)}</p><p className="mt-2 text-xs text-slate-500">{f.revenueBasisLabel} less committed costs</p></div><div className="bg-slate-950 p-6"><p className="text-sm text-slate-400">Cash position</p><p className={`mt-2 text-3xl font-bold ${f.cashPosition < 0 ? "text-red-400" : "text-amber-400"}`}>{money(f.cashPosition)}</p><p className="mt-2 text-xs text-slate-500">Cash received less cash paid</p></div><div className="bg-slate-950 p-6"><p className="text-sm text-slate-400">Customer outstanding</p><p className="mt-2 text-3xl font-bold">{money(f.customerOutstanding)}</p><p className="mt-2 text-xs text-slate-500">Issued invoice balances</p></div></div></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1fr_0.8fr]"><div className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Financial breakdown</h2><div className="mt-5 divide-y">{rows.map(([label,value], index) => <div key={label} className={`flex justify-between gap-4 py-3 text-sm ${(index === 8 || index === 10) ? "mt-2 border-t-2" : ""}`}><span className="text-slate-500">{label}</span><strong className={(label.includes("profit") || label.includes("position")) && value < 0 ? "text-red-700" : ""}>{money(value)}</strong></div>)}</div>{f.excludedLegacySubcontractorExpenses > 0 && <p className="mt-4 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">{money(f.excludedLegacySubcontractorExpenses)} in legacy “Subcontractor” expenses is excluded to prevent double counting structured subcontractor costs.</p>}</div><div className="space-y-5"><article className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Banknote className="text-emerald-600"/><div><p className="text-sm text-slate-500">Customer payments received</p><p className="text-2xl font-bold">{money(f.customerPayments)}</p></div></div></article><article className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><WalletCards className="text-amber-700"/><div><p className="text-sm text-slate-500">Subcontractors still owed</p><p className="text-2xl font-bold">{money(f.subcontractorOutstanding)}</p></div></div></article><article className="rounded-2xl border bg-white p-6 shadow-sm"><h3 className="font-bold">Project actions</h3><div className="mt-4 space-y-2">{!isArchived && <button onClick={() => setArchiveOpen(true)} className="inline-flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-amber-50 text-sm font-bold text-amber-800"><Archive size={17}/>Archive project</button>}<button onClick={() => setDeleteOpen(true)} className="inline-flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-red-50 text-sm font-bold text-red-700"><Trash2 size={17}/>Delete project</button></div></article></div></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-2"><Related title="Quotes" icon={FileText} empty="No quotes linked to this project.">{project.quotes.map((quote) => <Link key={quote.id} to={`/quotes/${quote.id}`} className="flex items-center justify-between gap-3 rounded-xl border p-4 hover:bg-slate-50"><div><p className="font-bold">{quote.quoteNumber} · {quote.title}</p><p className="mt-1 text-xs text-slate-500">{formatDate(quote.issueDate)}</p></div><div className="text-right"><p className="font-bold">{money(quote.totalAmount)}</p><span className={`mt-1 inline-flex rounded-full px-2 py-0.5 text-xs font-bold ${documentStatus(quote.status)}`}>{quote.status}</span></div></Link>)}</Related><Related title="Invoices" icon={ReceiptText} empty="No invoices linked to this project.">{project.invoices.map((invoice) => <Link key={invoice.id} to={`/invoices/${invoice.id}`} className="flex items-center justify-between gap-3 rounded-xl border p-4 hover:bg-slate-50"><div><p className="font-bold">{invoice.invoiceNumber} · {invoice.title}</p><p className="mt-1 text-xs text-slate-500">Paid {money(invoice.amountPaid)}</p></div><div className="text-right"><p className="font-bold">{money(invoice.totalAmount)}</p><span className={`mt-1 inline-flex rounded-full px-2 py-0.5 text-xs font-bold ${documentStatus(invoice.status)}`}>{invoice.status.replace("_", " ")}</span></div></Link>)}</Related><Related title="Expenses & receipts" icon={WalletCards} empty="No expenses linked to this project.">{project.expenses.map((expense) => <Link key={expense.id} to={`/expenses/${expense.id}`} className="flex items-center justify-between gap-3 rounded-xl border p-4 hover:bg-slate-50"><div><p className="font-bold">{expense.description}</p><p className="mt-1 text-xs text-slate-500">{expense.supplier || expense.category.replaceAll("_", " ")} · {expense.receipts.length} receipt(s)</p></div><p className="font-bold">{money(expense.amount)}</p></Link>)}</Related><Related title="Subcontractor work" icon={UsersRound} empty="No subcontractor costs linked to this project.">{project.subcontractorProjectCosts.map((cost) => <Link key={cost.id} to={`/subcontractors/${cost.subcontractor.id}`} className="flex items-center justify-between gap-3 rounded-xl border p-4 hover:bg-slate-50"><div><p className="font-bold">{cost.subcontractor.businessName || `${cost.subcontractor.firstName} ${cost.subcontractor.lastName || ""}`}</p><p className="mt-1 text-xs text-slate-500">{cost.description || "Project work"} · {cost.status.replace("_", " ")}</p></div><div className="text-right"><p className="font-bold">{money(cost.agreedAmount)}</p><p className="text-xs text-amber-700">Owing {money(cost.amountPending)}</p></div></Link>)}</Related></section>
    <Modal open={editOpen} title="Edit project" description="Update project information, dates, quoted value or status." onClose={() => setEditOpen(false)}><EditProjectForm project={project} onSuccess={async () => { await refresh(); setEditOpen(false); }} onCancel={() => setEditOpen(false)}/></Modal>
    <Modal open={archiveOpen} title="Archive project" description="The project remains in your records." onClose={() => setArchiveOpen(false)}><Confirm pending={archiveMutation.isPending} onCancel={() => setArchiveOpen(false)} onConfirm={() => archiveMutation.mutate()} label="Archive">Archive <strong>{project.name}</strong>?</Confirm></Modal>
    <Modal open={deleteOpen} title="Delete project permanently" description="This action cannot be undone." onClose={() => setDeleteOpen(false)}><Confirm danger pending={deleteMutation.isPending} onCancel={() => setDeleteOpen(false)} onConfirm={() => deleteMutation.mutate()} label="Delete">Delete <strong>{project.name}</strong> and its linked project records?</Confirm></Modal>
  </>;
}

function Related({ title, icon: Icon, empty, children }: { title: string; icon: typeof FileText; empty: string; children: React.ReactNode }) { const count = Array.isArray(children) ? children.length : children ? 1 : 0; return <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><Icon size={20} className="text-amber-700"/><h2 className="text-lg font-bold">{title}</h2></div><div className="mt-5 space-y-3">{count ? children : <p className="rounded-xl border border-dashed p-6 text-center text-sm text-slate-500">{empty}</p>}</div></section>; }
function Confirm({ children, label, danger, pending, onCancel, onConfirm }: { children: React.ReactNode; label: string; danger?: boolean; pending: boolean; onCancel: () => void; onConfirm: () => void }) { return <><div className="p-6 text-sm text-slate-700">{children}</div><div className="flex justify-end gap-3 border-t bg-slate-50 p-4"><button onClick={onCancel} className="rounded-xl border px-5 py-2 font-bold">Cancel</button><button disabled={pending} onClick={onConfirm} className={`rounded-xl px-5 py-2 font-bold disabled:opacity-50 ${danger ? "bg-red-700 text-white" : "bg-amber-400"}`}>{pending ? "Working…" : label}</button></div></>; }
