/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars */
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, ArrowLeft, CalendarDays, CheckCircle2, CircleAlert, CircleDollarSign, FilePlus2, FileText, MapPin, Pencil, Plus, ReceiptText, Trash2, Undo2, Upload, UserRound, UsersRound, WalletCards } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router";
import { getProjectOverview } from "../../analytics/api";
import type { OverviewInvoice, OverviewSubcontractorCost, ProjectOverview } from "../../analytics/types";
import { NewExpenseForm } from "../../expenses/components/NewExpenseForm";
import { ReceiptUpload } from "../../expenses/components/ReceiptUpload";
import { getReceiptDownloadUrl } from "../../expenses/api/receipts";
import { NewInvoiceForm } from "../../invoices/components/NewInvoiceForm";
import { RecordPaymentForm } from "../../invoices/components/RecordPaymentForm";
import type { Invoice } from "../../invoices/types/invoice";
import { NewQuoteForm } from "../../quotes/components/NewQuoteForm";
import { AddSubcontractorCostForm } from "../../subcontractors/components/AddSubcontractorCostForm";
import { RecordSubcontractorPaymentForm } from "../../subcontractors/components/RecordSubcontractorPaymentForm";
import type { SubcontractorProjectCost } from "../../subcontractors/types/subcontractor-cost";
import { Modal } from "../../../shared/components/ui/Modal";
import { archiveProject, deleteProject, updateProject } from "../api/projects";
import { EditProjectForm } from "../components/EditProjectForm";
import type { ProjectStatus } from "../types/project";

type Tab = "overview" | "expenses" | "receipts" | "invoices" | "subcontractors" | "quotes" | "activity";
type Dialog = "expense" | "invoice" | "quote" | "subcontractor" | null;
const tabs: { value: Tab; label: string }[] = [{value:"overview",label:"Overview"},{value:"expenses",label:"Expenses"},{value:"receipts",label:"Receipts"},{value:"invoices",label:"Invoices"},{value:"subcontractors",label:"Subcontractors"},{value:"quotes",label:"Quotes"},{value:"activity",label:"Activity"}];
const money = (value: string | number | null) => value === null ? "—" : new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD" }).format(Number(value));
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-AU", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)) : "Not scheduled";
const statusClasses = (status: ProjectStatus) => status === "ACTIVE" ? "bg-amber-50 text-amber-800" : status === "COMPLETED" ? "bg-emerald-100 text-emerald-700" : "bg-slate-200 text-slate-600";
const documentStatus = (status: string) => status === "PAID" || status === "ACCEPTED" ? "bg-emerald-100 text-emerald-700" : status === "OVERDUE" || status === "REJECTED" ? "bg-red-100 text-red-700" : "bg-amber-100 text-amber-700";

export function ProjectDetailsPage() {
  const { projectId } = useParams<{ projectId: string }>();
  const queryClient = useQueryClient(); const navigate = useNavigate();
  const [tab, setTab] = useState<Tab>("overview"); const [dialog, setDialog] = useState<Dialog>(null);
  const [editOpen,setEditOpen]=useState(false); const [archiveOpen,setArchiveOpen]=useState(false); const [deleteOpen,setDeleteOpen]=useState(false);
  const [completionOpen,setCompletionOpen]=useState(false);
  const [receiptExpenseId,setReceiptExpenseId]=useState<string|null>(null); const [paymentInvoice,setPaymentInvoice]=useState<OverviewInvoice|null>(null); const [paymentCost,setPaymentCost]=useState<OverviewSubcontractorCost|null>(null);
  const query = useQuery({ queryKey:["project-overview",projectId],queryFn:()=>getProjectOverview(projectId!),enabled:Boolean(projectId) });
  const refresh = async()=>{await Promise.all([queryClient.invalidateQueries({queryKey:["project-overview",projectId]}),queryClient.invalidateQueries({queryKey:["projects"]}),queryClient.invalidateQueries({queryKey:["expenses"]}),queryClient.invalidateQueries({queryKey:["invoices"]}),queryClient.invalidateQueries({queryKey:["quotes"]}),queryClient.invalidateQueries({queryKey:["subcontractor-costs"]}),queryClient.invalidateQueries({queryKey:["business-overview"]})]);};
  const statusMutation=useMutation({mutationFn:(status:"ACTIVE"|"COMPLETED")=>updateProject(projectId!,{status}),onSuccess:refresh});
  const archiveMutation=useMutation({mutationFn:()=>archiveProject(projectId!),onSuccess:async()=>{await refresh();setArchiveOpen(false);}});
  const deleteMutation=useMutation({mutationFn:()=>deleteProject(projectId!),onSuccess:async()=>{await queryClient.invalidateQueries({queryKey:["projects"]});navigate("/projects");}});
  const activity = useMemo(()=>{if(!query.data)return [];const p=query.data.project;return [...p.invoices.map(x=>({id:`i-${x.id}`,title:`Invoice ${x.invoiceNumber}`,detail:`${x.status.replaceAll("_"," ")} · ${money(x.totalAmount)}`,at:x.issueDate})),...p.expenses.map(x=>({id:`e-${x.id}`,title:`Expense added · ${x.description}`,detail:`${x.supplier||x.category.replaceAll("_"," ")} · ${money(x.amount)}`,at:x.expenseDate})),...p.quotes.map(x=>({id:`q-${x.id}`,title:`Quote ${x.quoteNumber}`,detail:x.title,at:x.issueDate})),...p.subcontractorProjectCosts.map(x=>({id:`s-${x.id}`,title:`Subcontractor work · ${x.subcontractor.firstName}`,detail:`${x.description||x.rateType} · ${money(x.agreedAmount)}`,at:""}))].sort((a,b)=>(b.at||"").localeCompare(a.at||""));},[query.data]);
  if(!projectId)return <ErrorPanel message="Invalid project ID."/>;
  if(query.isPending)return <div className="h-96 animate-pulse rounded-2xl bg-slate-200"/>;
  if(query.isError)return <ErrorPanel message={query.error.message} retry={()=>query.refetch()}/>;
  const {project,financials:f}=query.data; const customerName=project.customer?`${project.customer.firstName} ${project.customer.lastName}`:project.clientName||"No customer assigned"; const customerId=project.customerId??undefined;
  const open=(next:Dialog)=>setDialog(next); const close=()=>setDialog(null); const success=async()=>{await refresh();close();};
  return <>
    <Link to="/projects" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-slate-950"><ArrowLeft size={18}/>Back to projects</Link>
    <section className="mt-5 rounded-2xl border bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-5 lg:flex-row"><div><div className="flex flex-wrap items-center gap-3"><span className={`rounded-full px-3 py-1 text-xs font-bold ${statusClasses(project.status)}`}>{project.status}</span><span className="text-sm text-slate-500">{customerName}</span></div><h1 className="mt-3 text-3xl font-black text-slate-950">{project.name}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">{project.description||"No description added."}</p><div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-sm text-slate-600"><span className="inline-flex items-center gap-2"><MapPin size={16}/>{project.address||"No address"}</span><span className="inline-flex items-center gap-2"><CalendarDays size={16}/>{date(project.startDate)} — {date(project.endDate)}</span><span className="inline-flex items-center gap-2"><CircleDollarSign size={16}/>{money(project.quotedValue)}</span></div></div><div className="flex flex-wrap gap-2"><button onClick={()=>setEditOpen(true)} className="inline-flex h-11 items-center gap-2 rounded-xl bg-amber-400 px-4 text-sm font-bold"><Pencil size={17}/>Edit project</button>{project.status!=="ARCHIVED"&&<button onClick={()=>project.status==="COMPLETED"?statusMutation.mutate("ACTIVE"):setCompletionOpen(true)} className="inline-flex h-11 items-center gap-2 rounded-xl border px-4 text-sm font-bold">{project.status==="COMPLETED"?<Undo2 size={17}/>:<CheckCircle2 size={17}/>} {project.status==="COMPLETED"?"Mark active":"Complete"}</button>}</div></div></section>
    <nav className="sticky top-0 z-10 mt-5 flex gap-2 overflow-x-auto rounded-2xl border bg-white p-2 shadow-sm">{tabs.map(x=><button key={x.value} onClick={()=>setTab(x.value)} className={`shrink-0 rounded-xl px-4 py-2.5 text-sm font-bold ${tab===x.value?"bg-slate-950 text-white":"text-slate-600 hover:bg-slate-100"}`}>{x.label}</button>)}</nav>
    <div className="mt-5">
      {tab==="overview"&&<Overview project={project} f={f} customerName={customerName} setTab={setTab} open={open}/>}
      {tab==="expenses"&&<Workspace title="Project expenses" action="Add expense" onAction={()=>open("expense")} empty="No expenses yet" emptyDescription="Record your first cost for this project." count={project.expenses.length}>{project.expenses.map(x=><article key={x.id} className="flex flex-col justify-between gap-4 rounded-xl border p-4 sm:flex-row sm:items-center"><div><Link to={`/expenses/${x.id}`} className="font-bold hover:text-amber-800">{x.description}</Link><p className="mt-1 text-sm text-slate-500">{x.supplier||x.category.replaceAll("_"," ")} · {date(x.expenseDate)} · {x.receipts.length} receipt(s)</p></div><div className="flex items-center gap-3"><strong>{money(x.amount)}</strong><button onClick={()=>setReceiptExpenseId(x.id)} className="rounded-lg border px-3 py-2 text-xs font-bold">Add receipt</button></div></article>)}</Workspace>}
      {tab==="receipts"&&<Workspace title="Project receipts" action={project.expenses.length?"Upload receipt":undefined} onAction={()=>project.expenses[0]&&setReceiptExpenseId(project.expenses[0].id)} empty="No receipts" emptyDescription="Upload receipts against project expenses." count={project.expenses.reduce((n,x)=>n+x.receipts.length,0)}>{project.expenses.flatMap(expense=>expense.receipts.map((receipt,index)=><article key={(receipt as {id?:string}).id??`${expense.id}-${index}`} className="flex flex-col justify-between gap-3 rounded-xl border p-4 sm:flex-row sm:items-center"><div><p className="font-bold">{expense.supplier||expense.description}</p><p className="mt-1 text-sm text-slate-500">Expense: {expense.description} · {money(expense.amount)}</p></div><div className="flex gap-2"><a href={getReceiptDownloadUrl((receipt as {id:string}).id)} className="rounded-lg border px-3 py-2 text-sm font-bold">View</a><button onClick={()=>setReceiptExpenseId(expense.id)} className="rounded-lg bg-amber-100 px-3 py-2 text-sm font-bold text-amber-900">Replace / add</button></div></article>))}</Workspace>}
      {tab==="invoices"&&<Workspace title="Project invoices" action={customerId?"Create invoice":undefined} onAction={()=>open("invoice")} empty="No invoices yet" emptyDescription={customerId?"Create an invoice for this project.":"Link a customer to the project before invoicing."} count={project.invoices.length}>{project.invoices.map(x=><article key={x.id} className="grid gap-3 rounded-xl border p-4 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><Link to={`/invoices/${x.id}`} className="font-bold hover:text-amber-800">{x.invoiceNumber} · {x.title}</Link><p className="mt-1 text-sm text-slate-500">Due {date(x.dueDate)}</p></div><div className="text-sm"><p>Total <strong>{money(x.totalAmount)}</strong></p><p className="text-slate-500">Paid {money(x.amountPaid)} · Owing {money(x.balanceDue)}</p></div><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-1 text-xs font-bold ${documentStatus(x.status)}`}>{x.status.replaceAll("_"," ")}</span>{Number(x.balanceDue)>0&&x.status!=="CANCELLED"&&<button onClick={()=>setPaymentInvoice(x)} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Record payment</button>}</div></article>)}</Workspace>}
      {tab==="subcontractors"&&<Workspace title="Subcontractor work" action="Add subcontractor work" onAction={()=>open("subcontractor")} empty="No subcontractors yet" emptyDescription="Add subcontractor work to start tracking labour costs." count={project.subcontractorProjectCosts.length}>{project.subcontractorProjectCosts.map(x=><article key={x.id} className="rounded-xl border p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><Link to={`/subcontractors/${x.subcontractor.id}`} className="font-bold hover:text-amber-800">{x.subcontractor.businessName||`${x.subcontractor.firstName} ${x.subcontractor.lastName||""}`}</Link><p className="mt-1 text-sm text-slate-500">{x.description||"Project work"} · {x.rateType.replaceAll("_"," ")}{x.rate&&x.quantity?` · ${x.quantity} × ${money(x.rate)}`:""}</p></div><span className={`h-fit rounded-full px-2 py-1 text-xs font-bold ${documentStatus(x.status)}`}>{x.status.replaceAll("_"," ")}</span></div><div className="mt-4 grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-3 text-sm sm:grid-cols-4"><span>Agreed <strong className="block">{money(x.agreedAmount)}</strong></span><span>Paid <strong className="block">{money(x.amountPaid)}</strong></span><span>Outstanding <strong className="block">{money(x.amountPending)}</strong></span><span>{Number(x.amountPending)>0&&<button onClick={()=>setPaymentCost(x)} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Record payment</button>}</span></div></article>)}</Workspace>}
      {tab==="quotes"&&<Workspace title="Project quotes" action={customerId?"Create quote":undefined} onAction={()=>open("quote")} empty="No quotes yet" emptyDescription={customerId?"Create a quote for this project.":"Link a customer before creating a quote."} count={project.quotes.length}>{project.quotes.map(x=><Link key={x.id} to={`/quotes/${x.id}`} className="flex justify-between gap-4 rounded-xl border p-4 hover:bg-slate-50"><div><p className="font-bold">{x.quoteNumber} · {x.title}</p><p className="mt-1 text-sm text-slate-500">{date(x.issueDate)}</p></div><div className="text-right"><strong>{money(x.totalAmount)}</strong><span className={`mt-1 block rounded-full px-2 py-1 text-xs font-bold ${documentStatus(x.status)}`}>{x.status}</span></div></Link>)}</Workspace>}
      {tab==="activity"&&<Workspace title="Project activity" empty="No activity yet" emptyDescription="Project transactions will appear here." count={activity.length}>{activity.map(x=><article key={x.id} className="rounded-xl border p-4"><p className="font-bold">{x.title}</p><p className="mt-1 text-sm text-slate-500">{x.detail}{x.at?` · ${date(x.at)}`:""}</p></article>)}</Workspace>}
    </div>
    <div className="flex justify-end gap-2"><button onClick={()=>setArchiveOpen(true)} className="inline-flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-xs font-bold text-slate-600"><Archive size={15}/>Archive project</button><button onClick={()=>setDeleteOpen(true)} className="inline-flex items-center gap-2 rounded-xl border border-red-200 bg-white px-3 py-2 text-xs font-bold text-red-700"><Trash2 size={15}/>Delete project</button></div>
    <Modal open={dialog==="expense"} title="Add project expense" description={project.name} onClose={close}><NewExpenseForm projectId={project.id} projectName={project.name} onCancel={close} onSuccess={success}/></Modal>
    <Modal open={dialog==="invoice"} title="Create project invoice" description="Project and customer are already selected." onClose={close}>{customerId&&<NewInvoiceForm projectId={project.id} projectName={project.name} customerId={customerId} customerName={customerName} onCancel={close} onSuccess={success}/>}</Modal>
    <Modal open={dialog==="quote"} title="Create project quote" description="Project and customer are already selected." onClose={close}>{customerId&&<NewQuoteForm projectId={project.id} projectName={project.name} customerId={customerId} customerName={customerName} onCancel={close} onSuccess={success}/>}</Modal>
    <Modal open={dialog==="subcontractor"} title="Add subcontractor work" description={project.name} onClose={close}><AddSubcontractorCostForm projectId={project.id} projectName={project.name} onCancel={close} onSuccess={success}/></Modal>
    <Modal open={Boolean(receiptExpenseId)} title="Upload receipt" description="Attach the receipt to its owning expense." onClose={()=>setReceiptExpenseId(null)}>{receiptExpenseId&&<div className="p-6"><ReceiptUpload expenseId={receiptExpenseId} projectId={project.id} onSuccess={()=>{void refresh();setReceiptExpenseId(null);}}/></div>}</Modal>
    <Modal open={Boolean(paymentInvoice)} title="Record customer payment" description="Update this project’s invoice balance." onClose={()=>setPaymentInvoice(null)}>{paymentInvoice&&<RecordPaymentForm invoice={paymentInvoice as unknown as Invoice} onCancel={()=>setPaymentInvoice(null)} onSuccess={async()=>{await refresh();setPaymentInvoice(null);}}/>}</Modal>
    <Modal open={Boolean(paymentCost)} title="Record subcontractor payment" description="Update this project’s payable balance." onClose={()=>setPaymentCost(null)}>{paymentCost&&<RecordSubcontractorPaymentForm cost={paymentCost as unknown as SubcontractorProjectCost} onCancel={()=>setPaymentCost(null)} onSuccess={async()=>{await refresh();setPaymentCost(null);}}/>}</Modal>
    <Modal open={editOpen} title="Edit project" description="Update project information." onClose={()=>setEditOpen(false)}><EditProjectForm project={project} onCancel={()=>setEditOpen(false)} onSuccess={async()=>{await refresh();setEditOpen(false);}}/></Modal>
    <Modal open={completionOpen} title="Before completing this project" description="Review the financial and documentation position. These warnings do not block completion." onClose={()=>setCompletionOpen(false)}><div className="space-y-3 p-6">{f.completionChecklist.map((item)=><p key={item.key} className={`rounded-xl p-3 text-sm font-medium ${item.ok?"bg-emerald-50 text-emerald-800":"bg-amber-50 text-amber-900"}`}>{item.ok?"✓":"⚠"} {item.label}</p>)}</div><div className="flex justify-end gap-3 border-t bg-slate-50 p-4"><button onClick={()=>{setCompletionOpen(false);setTab("overview")}} className="rounded-xl border px-5 py-2 font-bold">Review issues</button><button onClick={()=>{statusMutation.mutate("COMPLETED");setCompletionOpen(false)}} className="rounded-xl bg-amber-400 px-5 py-2 font-bold">Complete anyway</button></div></Modal>
    <Modal open={archiveOpen} title="Archive project" description="The project remains in your records." onClose={()=>setArchiveOpen(false)}><Confirm pending={archiveMutation.isPending} onCancel={()=>setArchiveOpen(false)} onConfirm={()=>archiveMutation.mutate()} label="Archive">Archive <strong>{project.name}</strong>?</Confirm></Modal>
    <Modal open={deleteOpen} title="Delete project permanently" description="This action cannot be undone." onClose={()=>setDeleteOpen(false)}><Confirm danger pending={deleteMutation.isPending} onCancel={()=>setDeleteOpen(false)} onConfirm={()=>deleteMutation.mutate()} label="Delete">Delete <strong>{project.name}</strong> and linked project records?</Confirm></Modal>
  </>;
}

function Overview({project,f,customerName,setTab,open}:{project:ReturnType<typeof useProjectShape>;f:any;customerName:string;setTab:(tab:Tab)=>void;open:(dialog:Dialog)=>void}){const metrics=[["Quoted value",f.quotedValue],["Invoices issued",f.invoiceTotal],["Customer payments",f.customerPayments],["Customer outstanding",f.customerOutstanding],["Expenses",f.expenses],["Subcontractor agreed",f.subcontractorAgreed],["Subcontractor paid",f.subcontractorPaid],["Subcontractor outstanding",f.subcontractorOutstanding],["Estimated profit",f.estimatedProfit]];return <div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><div className="space-y-5"><section className="overflow-hidden rounded-2xl bg-slate-950 text-white"><div className="grid gap-px bg-slate-800 sm:grid-cols-3">{[["Estimated profit",f.estimatedProfit],["Cash position",f.cashPosition],["Customer outstanding",f.customerOutstanding]].map(([l,v])=><div key={l} className="bg-slate-950 p-6"><p className="text-sm text-slate-400">{l}</p><p className="mt-2 text-2xl font-black">{money(v)}</p></div>)}</div></section><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{metrics.map(([l,v])=><article key={l} className="rounded-2xl border bg-white p-4"><p className="text-xs font-bold uppercase text-slate-400">{l}</p><p className="mt-2 text-xl font-black">{money(v)}</p></article>)}</section></div><div className="space-y-5"><section className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-2"><UserRound className="text-amber-700"/><h2 className="font-bold">Customer</h2></div><p className="mt-4 text-lg font-black">{customerName}</p>{project.customer&&<><p className="mt-1 text-sm text-slate-500">{project.customer.email||"No email"} · {project.customer.phone||"No phone"}</p><Link to={`/customers/${project.customer.id}`} className="mt-4 inline-flex text-sm font-bold text-amber-800">View customer →</Link></>}</section><section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Quick actions</h2><div className="mt-4 grid gap-2">{[[WalletCards,"Add expense",()=>open("expense")],[ReceiptText,"Create invoice",()=>open("invoice")],[UsersRound,"Add subcontractor work",()=>open("subcontractor")],[Upload,"Upload receipt",()=>setTab("receipts")],[FileText,"Create quote",()=>open("quote")]].map(([Icon,label,action])=>{const I=Icon as typeof WalletCards;return <button key={label as string} onClick={action as ()=>void} className="inline-flex h-11 items-center gap-3 rounded-xl bg-slate-50 px-4 text-sm font-bold hover:bg-amber-50"><I size={17} className="text-amber-700"/>{label as string}</button>})}</div></section><section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Project management</h2><div className="mt-3 grid gap-2"><button onClick={()=>setTab("activity")} className="rounded-xl border px-4 py-2 text-sm font-bold">View activity</button></div></section></div></div>}
function useProjectShape(): ProjectOverview["project"] { throw new Error("Type helper only"); }
function Workspace({title,action,onAction,empty,emptyDescription,count,children}:{title:string;action?:string;onAction?:()=>void;empty:string;emptyDescription:string;count:number;children:React.ReactNode}){return <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-xl font-black">{title}</h2><p className="mt-1 text-sm text-slate-500">{count} {count===1?"record":"records"}</p></div>{action&&onAction&&<button onClick={onAction} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-amber-400 px-4 text-sm font-bold"><Plus size={17}/>{action}</button>}</div><div className="mt-5 space-y-3">{count?children:<div className="rounded-xl border border-dashed p-8 text-center"><FilePlus2 className="mx-auto text-slate-300"/><p className="mt-3 font-bold">{empty}</p><p className="mt-1 text-sm text-slate-500">{emptyDescription}</p>{action&&onAction&&<button onClick={onAction} className="mt-4 rounded-xl bg-amber-400 px-4 py-2 text-sm font-bold">{action}</button>}</div>}</div></section>}
function ErrorPanel({message,retry}:{message:string;retry?:()=>void}){return <div className="flex gap-3 rounded-2xl border border-red-200 bg-red-50 p-6 text-red-700"><CircleAlert/><div><strong>Project could not be loaded</strong><p className="mt-1 text-sm">{message}</p>{retry&&<button onClick={retry} className="mt-3 rounded-lg bg-red-700 px-3 py-2 text-sm font-bold text-white">Try again</button>}</div></div>}
function Confirm({children,label,danger,pending,onCancel,onConfirm}:{children:React.ReactNode;label:string;danger?:boolean;pending:boolean;onCancel:()=>void;onConfirm:()=>void}){return <><div className="p-6 text-sm">{children}</div><div className="flex justify-end gap-3 border-t bg-slate-50 p-4"><button onClick={onCancel} className="rounded-xl border px-5 py-2 font-bold">Cancel</button><button disabled={pending} onClick={onConfirm} className={`rounded-xl px-5 py-2 font-bold ${danger?"bg-red-700 text-white":"bg-amber-400"}`}>{pending?"Working…":label}</button></div></>}
