import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View, type PressableProps, type TextInputProps, type ViewProps } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors, radius, spacing } from "../theme";

export function Screen({ style, ...props }: ViewProps) { return <SafeAreaView edges={["top"]} style={[styles.screen, style]} {...props} />; }
export function Card({ style, ...props }: ViewProps) { return <View style={[styles.card, style]} {...props} />; }
export function AppButton({ title, loading, variant = "primary", style, ...props }: PressableProps & { title: string; loading?: boolean; variant?: "primary" | "secondary" | "danger" }) {
  return <Pressable accessibilityRole="button" disabled={loading || props.disabled} style={(state) => [styles.button, variant === "secondary" && styles.buttonSecondary, variant === "danger" && styles.buttonDanger, state.pressed && { opacity: .75 }, (loading || props.disabled) && { opacity: .5 }, typeof style === "function" ? style(state) : style]} {...props}>{loading ? <ActivityIndicator color={variant === "secondary" ? colors.text : "white"} /> : <Text style={[styles.buttonText, variant === "secondary" && { color: colors.text }]}>{title}</Text>}</Pressable>;
}
export function AppInput({ label, error, style, ...props }: TextInputProps & { label: string; error?: string }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput placeholderTextColor={colors.muted} style={[styles.input, error && { borderColor: colors.danger }, style]} {...props} />{error ? <Text style={styles.errorText}>{error}</Text> : null}</View>; }
export function Header({ title, subtitle, action }: { title: string; subtitle?: string; action?: React.ReactNode }) { return <View style={styles.header}><View style={{ flex: 1 }}><Text style={styles.title}>{title}</Text>{subtitle ? <Text style={styles.subtitle}>{subtitle}</Text> : null}</View>{action}</View>; }
export function MoneyValue({ value, color }: { value: number | string; color?: string }) { return <Text style={[styles.money, color ? { color } : null]}>{new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD" }).format(Number(value ?? 0))}</Text>; }
export function StatusBadge({ status }: { status: string }) { const positive = ["ACTIVE", "PAID", "COMPLETED"].includes(status); const danger = ["OVERDUE", "CANCELLED"].includes(status); return <View style={[styles.badge, { backgroundColor: positive ? "#DCFCE7" : danger ? "#FEE2E2" : "#FEF3C7" }]}><Text style={{ color: positive ? colors.success : danger ? colors.danger : colors.primaryDark, fontSize: 11, fontWeight: "800" }}>{status.replaceAll("_", " ")}</Text></View>; }
export function LoadingState() { return <View style={styles.state}><ActivityIndicator color={colors.primaryDark} size="large"/><Text style={styles.subtitle}>Loading…</Text></View>; }
export function ErrorState({ message, retry }: { message?: string; retry?: () => void }) { return <View style={styles.state}><Text style={styles.errorTitle}>Couldn’t load this</Text><Text style={styles.subtitle}>{message ?? "Check your connection and try again."}</Text>{retry ? <AppButton title="Try again" variant="secondary" onPress={retry}/> : null}</View>; }
export function EmptyState({ title, message }: { title: string; message: string }) { return <Card style={styles.state}><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.subtitle}>{message}</Text></Card>; }
const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background }, card: { backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, padding: spacing.md },
  button: { minHeight: 50, borderRadius: radius.sm, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center", paddingHorizontal: spacing.md }, buttonSecondary: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, buttonDanger: { backgroundColor: colors.danger }, buttonText: { color: "#fff", fontWeight: "800", fontSize: 16 },
  field: { gap: 6 }, label: { color: colors.text, fontSize: 14, fontWeight: "700" }, input: { minHeight: 50, paddingHorizontal: 14, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.sm, color: colors.text, fontSize: 16 }, errorText: { color: colors.danger, fontSize: 12 },
  header: { flexDirection: "row", alignItems: "center", gap: spacing.md, paddingHorizontal: spacing.md, paddingTop: spacing.sm, paddingBottom: spacing.md }, title: { fontSize: 28, fontWeight: "900", color: colors.text, letterSpacing: -.5 }, subtitle: { color: colors.muted, lineHeight: 20 }, money: { color: colors.text, fontWeight: "900", fontSize: 20 }, badge: { alignSelf: "flex-start", borderRadius: 99, paddingHorizontal: 9, paddingVertical: 5 }, state: { flex: 1, minHeight: 180, alignItems: "center", justifyContent: "center", gap: spacing.md, padding: spacing.xl, backgroundColor: colors.background }, errorTitle: { fontWeight: "800", color: colors.danger, fontSize: 18 }, emptyTitle: { fontWeight: "800", color: colors.text, fontSize: 17 },
});
export const uiStyles = styles;
