import { useMutation, useQueryClient } from "@tanstack/react-query";
import { CircleAlert, LoaderCircle, LockKeyhole, Mail } from "lucide-react";
import { type FormEvent, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router";
import { login } from "../api/auth";
import { AuthShell } from "../components/AuthShell";
import { authQueryKey } from "../hooks/useCurrentUser";
const input="mt-2 h-12 w-full rounded-xl border border-slate-200 pl-11 pr-3 text-sm outline-none focus:border-slate-500 focus:ring-2 focus:ring-slate-200";
export function LoginPage(){const [email,setEmail]=useState("");const[password,setPassword]=useState("");const queryClient=useQueryClient();const navigate=useNavigate();const location=useLocation();const mutation=useMutation({mutationFn:login,onSuccess:async(user)=>{queryClient.clear();queryClient.setQueryData(authQueryKey,user);const state=location.state as {from?:string}|null;navigate(state?.from||"/",{replace:true});}});function submit(e:FormEvent){e.preventDefault();mutation.reset();mutation.mutate({email:email.trim().toLowerCase(),password});}return <AuthShell title="Welcome back" description="Log in to continue managing your trade business."><form onSubmit={submit} className="space-y-5">{mutation.isError&&<p className="flex gap-2 rounded-xl bg-red-50 p-4 text-sm text-red-700"><CircleAlert size={19}/>{mutation.error.message}</p>}<label className="block text-sm font-bold text-slate-700">Email<div className="relative"><Mail className="absolute left-3.5 top-1/2 mt-1 -translate-y-1/2 text-slate-400" size={18}/><input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} required autoComplete="email" className={input} placeholder="you@business.com.au"/></div></label><label className="block text-sm font-bold text-slate-700">Password<div className="relative"><LockKeyhole className="absolute left-3.5 top-1/2 mt-1 -translate-y-1/2 text-slate-400" size={18}/><input type="password" value={password} onChange={(e)=>setPassword(e.target.value)} required autoComplete="current-password" className={input}/></div></label><button disabled={mutation.isPending} className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-amber-400 font-bold disabled:opacity-50">{mutation.isPending&&<LoaderCircle className="animate-spin" size={18}/>}Log in</button><p className="text-center text-sm text-slate-500">New to Tradie Assistant? <Link to="/register" className="font-bold text-slate-950 underline">Create account</Link></p><div className="rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-500"><strong>Local demo:</strong> demo@tradieassistant.com / TradieDemo2026!</div></form></AuthShell>}
