import { useMutation, useQueryClient } from "@tanstack/react-query";
import { CircleAlert, LoaderCircle } from "lucide-react";
import { type FormEvent, useState } from "react";
import { Link, useNavigate } from "react-router";
import { register } from "../api/auth";
import { AuthShell } from "../components/AuthShell";
import { authQueryKey } from "../hooks/useCurrentUser";
const input="mt-2 h-12 w-full rounded-xl border border-slate-200 px-3.5 text-sm outline-none focus:border-slate-500 focus:ring-2 focus:ring-slate-200";
export function RegisterPage(){const[form,setForm]=useState({firstName:"",lastName:"",businessName:"",email:"",password:"",confirm:""});const[validation,setValidation]=useState<string|null>(null);const queryClient=useQueryClient();const navigate=useNavigate();const mutation=useMutation({mutationFn:register,onSuccess:(user)=>{queryClient.clear();queryClient.setQueryData(authQueryKey,user);navigate("/settings",{replace:true});}});function submit(e:FormEvent){e.preventDefault();setValidation(null);mutation.reset();if(form.password.length<8)return setValidation("Password must be at least 8 characters.");if(form.password!==form.confirm)return setValidation("Passwords do not match.");mutation.mutate({firstName:form.firstName.trim(),lastName:form.lastName.trim(),businessName:form.businessName.trim()||null,email:form.email.trim().toLowerCase(),password:form.password});}const change=(name:string,value:string)=>setForm((current)=>({...current,[name]:value}));return <AuthShell title="Create your workspace" description="Set up your private Tradie Assistant account in less than a minute."><form onSubmit={submit} className="space-y-4">{(validation||mutation.isError)&&<p className="flex gap-2 rounded-xl bg-red-50 p-4 text-sm text-red-700"><CircleAlert size={19}/>{validation||mutation.error?.message}</p>}<div className="grid gap-4 sm:grid-cols-2"><Field label="First name" value={form.firstName} onChange={(v)=>change("firstName",v)}/><Field label="Last name" value={form.lastName} onChange={(v)=>change("lastName",v)}/></div><Field label="Business name (optional)" value={form.businessName} onChange={(v)=>change("businessName",v)}/><Field label="Email" type="email" value={form.email} onChange={(v)=>change("email",v)} autoComplete="email"/><div className="grid gap-4 sm:grid-cols-2"><Field label="Password" type="password" value={form.password} onChange={(v)=>change("password",v)} autoComplete="new-password"/><Field label="Confirm password" type="password" value={form.confirm} onChange={(v)=>change("confirm",v)} autoComplete="new-password"/></div><p className="text-xs text-slate-500">Use at least 8 characters. A longer passphrase is encouraged.</p><button disabled={mutation.isPending} className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-amber-400 font-bold disabled:opacity-50">{mutation.isPending&&<LoaderCircle className="animate-spin" size={18}/>}Create account</button><p className="text-center text-sm text-slate-500">Already have an account? <Link to="/login" className="font-bold text-slate-950 underline">Log in</Link></p></form></AuthShell>}
function Field({label,value,onChange,type="text",autoComplete}:{label:string;value:string;onChange:(value:string)=>void;type?:string;autoComplete?:string}){return <label className="block text-sm font-bold text-slate-700">{label}<input type={type} value={value} onChange={(e)=>onChange(e.target.value)} required={!label.includes("optional")} autoComplete={autoComplete} className={input}/></label>}
